version: '3.6'

services:
  # 开发环境数据库
  postgresql_dev:
    restart: always
    image: postgres
    environment:
      - DB_USER=rick
      - DB_PASS=rick
      - DB_NAME=mapdog_dev
    ports:
      - "3456:5432"

  # 测试环境数据库
  postgresql_test:
    restart: always
    image: postgres
    environment:
      - DB_USER=rick
      - DB_PASS=rick
      - DB_NAME=mapdog_test
    ports:
      - "5555:5432"
