version: '3.6'
# TODO: 不同项目端口占用
services:
  # 开发环境数据库
  postgresql_mapdog_dev:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=mapdog
      - POSTGRES_PASSWORD=mapdog
      - POSTGRES_DB=mapdog_dev
    ports:
      - "3456:5432"

  # 测试环境数据库
  postgresql_mapdog_test:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=rick
      - POSTGRES_PASSWORD=rick
      - POSTGRES_DB=mapdog_test
    ports:
      - "5555:5432"
